name: docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@d8ef131ecec0352ce0e39b81b0a6d95def58fe2f  # v1
        with:
          crystal: latest

      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e  # v2

      - name: Install dependencies
        run: shards install
        env:
          SHARDS_OPTS: --ignore-crystal-version

      - name: Generate
        run: crystal docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@049a95c516cd5723d8cfde79dc7a79fcdcbd6c97  # 4.0.0
        with:
          branch: gh-pages
          folder: docs
